import { readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { subsetFontCss } from '../lib/font-subset';

async function sources(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const result: string[] = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) result.push(...await sources(path));
    else if (/\.(tsx?|css)$/.test(entry.name) && entry.name !== 'fonts.css') result.push(await readFile(path, 'utf8'));
  }
  return result;
}
const content = (await Promise.all(['app', 'components', 'data'].map(sources))).flat().join('\n');
const css = (await Promise.all([400, 500, 600].map(weight => readFile(`node_modules/@fontsource/noto-sans-jp/${weight}.css`, 'utf8')))).join('\n');
const output = '/* Generated by bun run fonts:generate. Do not edit directly. */\n' + subsetFontCss(css, content);
await writeFile('app/fonts.css', output);
console.log(`Fonts: ${Buffer.byteLength(output).toLocaleString()} bytes of CSS for the current content.`);
